### ISSUE TITLE
cant connect with mitproxy

### ISSUE THREAD

**Issue by thomas70** [kayjei/adax_wifi#3]
My adax app fails with "cant collect information" when using mitmproxy. I have installed the certificate. Any tips ?

**Comment by kayjei** [comment]
Sounds like you doesn't allow traffic forwarding, either in mitm or in the machine (Linux?).
How did you set it up? Docker, physical machine?

**Comment by thomas70** [comment]
i run it on a physical machine. Regular browsing working fine

**Comment by kayjei** [comment]
Do you see the regular browsing in the proxy? Seems strange, haven't seen that. 
Are you on iphone or Android?
I'm afraid I don't have very much experience ot troubleshooting the proxy

**Comment by thomas70** [comment]
I have a Android phone. Samsung Galaxy S10

**Comment by kayjei** [comment]
I found a thread on this topic, please try to find the proxy solution here. 
https://github.com/mitmproxy/mitmproxy/issues/2054

**Comment by thomas70** [comment]
Tried on a old tablet. Worked fine

**Comment by joggs** [comment]
getting the problem on nadroid 7 and up and also on my ipad with latest ios.
