### ISSUE TITLE
Heater signature changes each time I enter the zone settings for a zone

### ISSUE THREAD

**Issue by joggs** [kayjei/adax_wifi#7]
Major problem.
Each time I enter Zones -> "zone name" in the adax app and then check the heater signature value in the proxy it has changed to a new value.
This means that you have to update parameters.py each time after entering the zone page in the adax app which of course is not an option.
Please try to reproduce.

**Comment by kayjei** [comment]
Hi, 
No, the previous signature will still be valid.
Please try to use the dev branch rather than master. Dev has support for Android and multiple zones

**Comment by joggs** [comment]
Aha, so all previous signatures will be valid for that heater? Out of curiosity do you know why and how? :-)
I'll try the dev branch and will try more than two zones after I have installed my remaining 4 heaters.
Thanks for a great integration!

**Comment by kayjei** [comment]
I have no idea! My signatures were extracted in august and are still valid :-)
I am trying to understand the authentication process to be able to complete the integration, but no luck so far.
